### ISSUE TITLE
Error Epsilon_Section_Navigation_Menu

### ISSUE THREAD

**Issue by rickyanwar** [ColorlibHQ/Mosh#19]
Fatal error: Uncaught Error: Class 'Epsilon_Section_Navigation_Menu'

Fatal error: Uncaught Error: Class 'Epsilon_Section_Navigation_Menu' not found in /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/class-epsilon-init-dashboard.php:172 Stack trace: #0 /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/class-epsilon-init-dashboard.php(67): Epsilon_init_Dashboard->init_nav_menus() #1 /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/class-epsilon-init-dashboard.php(82): Epsilon_init_Dashboard->__construct(Object(WP_Theme)) #2 /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/classes/Class-Config.php(54): Epsilon_init_Dashboard::get_instance() #3 /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/classes/Class-Config.php(40): Mosh->init() #4 /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/functions.php(111): Mosh->__construct() #5 /opt/lampp/htdocs/wordpress/wp-settings.php(499): include('/opt/lampp/htdo...') #6 /opt/lampp/htdocs/wordpress/wp-config.php(90): require_once('/opt/lampp/htdo...') #7 /opt/lampp/htdocs/wordpress/ in /opt/lampp/htdocs/wordpress/wp-content/themes/Mosh-master/inc/class-epsilon-init-dashboard.php on line 172

**Comment by cristianraiber** [comment]
That's not how you clone this repository. You need to clone with submodules.

If you use Git CLI, use this: git clone --recursive
