### ISSUE TITLE
Demo data import error issue

### ISSUE THREAD

**Issue by codepixar** [ColorlibHQ/Mosh#5]
Hello,
When import demo data nav bar show an error ( http://prntscr.com/l2swas )because of empty menu title ( http://prntscr.com/l2swv2 ). We are working on update this theme. Could you please fix this issue on your live site and give us new demo file . After that we will PR.
We have already updated the theme in our local. Following issues

1. Elementor default element styling
2. Update epsilon framework
3. Update epsilon dashboard

**Comment by cristianraiber** [comment]
@codepixar - I recommend using: https://local.getflywheel.com instead of MAMP. Being able to replicate the dev environment you're going to be deploying to, helps a lot. 

I'm having trouble spotting this issue on Colorlib's live demo site: https://colorlib.com/mosh/

**Comment by codepixar** [comment]
@cristianraiber Could you please check http://prntscr.com/l2swv2 this in your menu inside WordPress dashboard.

Thanks. Akash

**Comment by cristianraiber** [comment]
@codepixar - this issue appears to be coming from your malformed XML :) Once you fix that XML, I can re-upload, re-do the demo and re-export. 

Thanks,
Cristian.

**Comment by cristianraiber** [comment]
@codepixar - Portfolio CPT was added there instead of it being created through Elementor and a page. Also, in your original demo XML, the `/portfolio/` page was inaccessible / throwing a not found error. 

Given that individual portfolio URLs don't even exist, I don't see the need for a CPT. I hope you understand that I'm saying you have to re-do the portfolio part, only through Elementor, no CPT. Once that's done, please open a PR and I'll do the final demo export.

Thank you,
Cristian.

**Comment by cristianraiber** [comment]
@codepixar - any updates on this?

**Comment by codepixar** [comment]
@cristianraiber  - Yes i do some thing with confused 😊. Portfolio element provide elementor in elementor pro version.Portfolio section consist with filter and load more button in the mosh theme that why I was used CPT. You said that not to use CPT so i do removing filter and load more button. 
Please see screenshot.
http://prntscr.com/l4p43e
http://prntscr.com/l4p49s
If you have better idea please suggest me.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - you could add a new field in your portfolio item called "tag" and allow users to tag their products. Based on these tags, you can create filters. Does this make any sense? Also, load more button can be still used, if the user adds 20 portfolio items but only wants to show 10 at a time.

**Comment by codepixar** [comment]
@cristianraiber - Thanks for your suggestion. I'm working and try to my best.

Thanks.

**Comment by cristianraiber** [comment]
@codepixar - Let's see what comes out of it :) I'm sure you'll be fine!

**Comment by cristianraiber** [comment]
Good job with this.
