### ISSUE TITLE
Privacy tab theme about page

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/Mosh#7]
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/7841556/46739444-3aa17800-cca9-11e8-96b6-71cefee18e69.png">

**Comment by codepixar** [comment]
@ cristianraiber - I don't understand. Could you please describe.
Thanks.

**Comment by cristianraiber** [comment]
@codepixar - You see in the above screenshot the "Hide Customizer Recommended plugins" showing up twice? They shouldn't be showing up at all. This feature isn't used in this theme.
